### ISSUE TITLE
Selling units

### ISSUE THREAD

**Issue by Austinm53** [4c65736975/additionalUnits#6]
The units for the selling prices are still set to 1000 liters. Can we get this changed. I also added in the bushel conversion factor myself and want to be able to sell by the bushel.

**Comment by 4c65736975** [comment]
Unit is unit, price will always be the same. Regardless of whether it is converted to liters or not, it is the same mass after all.

**Comment by KingArthurLV** [comment]
I agree that it is not possible to change core game logic, but I wonder if somehow FS22_additionalUnits can work in conjunction with [FS22_TSStockCheck](https://www.farming-simulator.com/mod.php?mod_id=257611) to make it show different mass and accordingly also money value of that mass.

**Comment by Incompertus** [comment]
> Unit is unit, price will always be the same. Regardless of whether it is converted to liters or not, it is the same mass after all.

i know this is old but liters is not mass it's volume and the sell prices are per 1k liters and ThundRFS Unitconvert can change the prices from liters to Kg and bushels

**Comment by 4c65736975** [comment]
> > Unit is unit, price will always be the same. Regardless of whether it is converted to liters or not, it is the same mass after all.
> 
> i know this is old but liters is not mass it's volume and the sell prices are per 1k liters and ThundRFS Unitconvert can change the prices from liters to Kg and bushels

If 1000 liters (or 1 m³) of wheat have a volume of 750 kg, then we can say that 1000 liters of wheat also weigh 750 kg. The volume and mass of wheat (or whatever else) are correlated.

Similarly, if the price for 1000 liters of wheat is 500$, then the price for 750 kg will be the same. This is because both quantities are related in terms of weight. If 1000 liters of wheat weigh 750 kg, then the price for 750 kg of wheat will be the same as for 1000 liters, which is 500$.

So I don't understand at all what you are writing about, weight is weight. Exactly as if you were arguing that 1 kg of feathers is lighter than 1 kg of bricks...

**Comment by Incompertus** [comment]
what i'm saying is 1 liter of water is 1Kg but 1 liter of feathers is not 1 Kg

liters is not the same as Kg :)

**Comment by 4c65736975** [comment]
> what i'm saying is 1 liter of water is 1Kg but 1 liter of feathers is not 1 Kg
> 
> 
> 
> liters is not the same as Kg :)

Because it depends on the volume, as explained above.

1000l of wheat is not 1000kg but 750kg,
1 liter of wheat is not 1 kg of wheat but 0.75 kg.
